Maintainer instructions for making releases
===========================================

Introduction
------------

The point of this document is to describe all steps required to make a
proper release of the libu2f-server project.

Details
-------

* Make sure your working environment is up to date.  Confirm with:
  +git checkout master && git pull && git diff+.

* Make sure the version number in +configure.ac+ has been incremented in +AC_INIT+.

* Make sure the libtool shared library version has been incremented properly, see http://www.gnu.org/software/libtool/manual/html_node/Versioning.html Always increment +LT_REVISION+ on every release -- it makes it possible to have multiple releases installed concurrently which helps testing.

* Make sure +NEWS+ describes all changes since the last release.  Use https://github.com/Yubico/libu2f-server/commits/master to review. Running +make distcheck+ will also produce a Changelog file.

* Change the '(unreleased)' part in NEWS to '(released 20XX-YY-ZZ)' and commit that with a note 'Version Q.P'.

* Run +make release+.

* Increment version number in +configure.ac+ and add a +NEWS+ template for the next release.
